Exception-Handlers/MediPal

README.md
Added a "checkin" to the README so everyone can familiar committing to main.
=> checkin: kai

.gitignore, lib/login..dart, lib/main.dart
Added login page and page 4 with login sample.
=> Added login page and page 4 with login sample.

lib/main.dart, lib/pages/SignUp.dart
shoe's ui for the sign up page
=> added ui to sign up

lib/form_patient.dart, lib/forms/general_info.dart, lib/forms/health_conditions.dart, lib/main.dart
added multi page navigation to patient form
added background color to pages
=> multi page patient form

lib/main.dart, lib/pages/forgotpasswd.dart, pubspec.lock, pubspec.yaml
=> Forgot passwd start

lib/pages/SignUp.dart
=> Fixed a few things

lib/form_gen_patient_info.dart, lib/main.dart, lib/pages/forgotpasswd.dart, lib/pages/login.dart
Shu's code for the forgot passwd page that was causing errors on his emulator. SHU THIS IS YOUR CODE ACCEPT IT
=> Forgot Passwd

lib/form_gen_patient_info.dart, lib/main.dart, lib/pages/forgotpasswd.dart, lib/pages/login.dart
Added flare to login page to make it better and did forgot password page with shu's help.
=> LoginPage Redux

lib/pages/patientpage.dart
=> Fix PatientPage

lib/forms/input_template.dart, lib/pages/patientpage.dart
made the data placeholders be in list format instead of as individual variable rows so that the sizes can be dynamic based on amount of patient info input.
=> Finished patient page with fix

lib/pages/patientpage.dart
changed stuff in patient page cause why not
=> Ditto last commit i made

lib/pages/patientpage.dart
=> Added some comments

lib/pages/appointment.dart
Made the "Create Appointment" button and switched position of MediPal Logo and "Appointment" title text.
=> Appointment Page Update

lib/objects/appointment_patient.dart, lib/pages/appointment_date.dart
Added new objects file for the dropdown search. Patient data now accessible and DOB fixed to not include time zone
=> updated dropdown search and fixed DOB to not include time zone

lib/form_patient.dart, lib/forms/family.dart, lib/forms/file_display.dart, lib/forms/files.dart, lib/forms/files_list.dart, lib/forms/general_info.dart, lib/forms/patient_data.dart, lib/objects/patient.dart, lib/pages/signup.dart, linux/flutter/generated_plugin_registrant.cc, linux/flutter/generated_plugins.cmake, macos/Flutter/GeneratedPluginRegistrant.swift, pubspec.lock, pubspec.yaml, windows/flutter/generated_plugin_registrant.cc, windows/flutter/generated_plugins.cmake
file list add/display working
some bugs for submitting edits fixed
patient data page now displays most info correctly
=> patient form/data page updated

lib/chat/chat_list.dart, lib/forms/general_info.dart, lib/pages/appointment_page.dart, lib/pages/dashboard.dart, lib/pages/patient_list.dart, lib/patient_form.dart
Navbar works for main pages for now, may add in additional as we flesh out the details.
=> Navbar done

lib/patient_form.dart
begun working on changing form ui and styling it.
=> Begun work on form

lib/objects/navbar.dart, lib/objects/show_all.dart, lib/pages/dashboard.dart, lib/pages/patient_form.dart, lib/pages/patient_list.dart, lib/pages/user_patients.dart
Abstracted the navbar, as well as a button to go to all patients from user patients. Navbar navigation from dashboard goes to user patients when you click "patients", have not changed for other pages navigation yet to make sure its working as should be first. Also added some styling to user patients.
=> Navbar abstraction

lib/chat/chat_list.dart
Chatlist shows the names of the practitioners.
=> Chatlist shows names

lib/main.dart, lib/pages/account_details.dart, lib/pages/signup.dart
=> Settings page fixes
